services:
  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: wenslo-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - wenslo-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: wenslo-frontend
    ports:
      - "5001:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - wenslo-network

networks:
  wenslo-network:
    driver: bridge
